default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        types: [python]
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.2
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: local
    hooks:
    -   id: c-format
        name: c-format
        entry: make hook-format
        language: system
        types: ["c", "header"]
    -   id: c-lint
        name: c-lint
        entry: make hook-lint
        language: system
        types: ["c", "header"]
    -   id: c-static-analysis
        name: c-static-analysis
        entry: make hook-static-analysis
        language: system
        types: ["c", "header"]
