FROM python:3.6.7-slim

LABEL maintainer="jparkie <https://github.com/jparkie>"
LABEL description="A Docker image used for testing cookiecutter-c projects"

# Install Python Project Tools:
# - C Interoperability: cffi
# - Property Testing: hypothesis
# - Testing Framework: pytest
RUN pip3 install \
  cffi \
  hypothesis \
  pytest

WORKDIR /repo
